<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.AspNetCoreServer.Hosting" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Formatting.Compact" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../PDS.Shared/PDS.Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="PDS.Tests" />
  </ItemGroup>
</Project>
