<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AWSSDK.DynamoDBv2" />
    <PackageReference Include="FluentValidation" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="PDS.Tests" />
  </ItemGroup>
</Project>
