/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListProjects"];
        put?: never;
        post: operations["CreateProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetProject"];
        put: operations["UpdateProject"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/projects/{id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ArchiveProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/projects/{id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["RestoreProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {unknown} */
        AuthMode: "Gateway" | "Development";
        ClientAuthConfig: {
            mode: components["schemas"]["AuthMode"];
            authority: null | string;
            clientId: null | string;
            logoutDomain: null | string;
        };
        ClientConfig: {
            productName: string;
            logoUrl: null | string;
            primaryColor: string;
            currency: string;
            culture: string;
            timeZone: string;
            auth: components["schemas"]["ClientAuthConfig"];
        };
        CreateProjectRequest: {
            code: string;
            name: string;
            site: components["schemas"]["SiteDto"];
            stage: null | components["schemas"]["ProjectStage"];
            status: null | components["schemas"]["ProjectStatus"];
            /** Format: date */
            plannedStart: null | string;
            /** Format: date */
            plannedCompletion: null | string;
            /** Format: date */
            actualStart: null | string;
            /** Format: date */
            actualCompletion: null | string;
            /** Format: double */
            budgetAmount: null | number;
            projectManager: null | string;
            description: null | string;
        };
        HttpValidationProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
            errors?: {
                [key: string]: string[];
            };
        };
        Me: {
            id: string;
            name: string;
            email: null | string;
            roles: string[];
        };
        PagedResultOfProjectListItem: {
            items: components["schemas"]["ProjectListItem"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int32 */
            totalCount: number;
        };
        ProjectDetails: {
            /** Format: uuid */
            id: string;
            code: string;
            name: string;
            site: components["schemas"]["SiteDto"];
            stage: components["schemas"]["ProjectStage"];
            status: components["schemas"]["ProjectStatus"];
            /** Format: date */
            plannedStart: null | string;
            /** Format: date */
            plannedCompletion: null | string;
            /** Format: date */
            actualStart: null | string;
            /** Format: date */
            actualCompletion: null | string;
            /** Format: double */
            budgetAmount: null | number;
            currency: string;
            projectManager: null | string;
            description: null | string;
            isArchived: boolean;
            /** Format: date-time */
            createdAt: string;
            createdBy: string;
            /** Format: date-time */
            updatedAt: string;
            updatedBy: string;
            /** Format: int64 */
            version: number;
        };
        ProjectListItem: {
            /** Format: uuid */
            id: string;
            code: string;
            name: string;
            stage: components["schemas"]["ProjectStage"];
            status: components["schemas"]["ProjectStatus"];
            suburb: null | string;
            city: string;
            /** Format: date */
            plannedCompletion: null | string;
            /** Format: double */
            budgetAmount: null | number;
            currency: string;
            isArchived: boolean;
        };
        /** @enum {unknown} */
        ProjectStage: "Acquisition" | "Feasibility" | "Design" | "Consenting" | "Construction" | "Sales" | "Completed";
        /** @enum {unknown} */
        ProjectStatus: "OnTrack" | "AtRisk" | "Delayed" | "OnHold" | "Cancelled";
        SiteDto: {
            addressLine: string;
            suburb: null | string;
            city: string;
            region: null | string;
            postcode: null | string;
            legalDescription: null | string;
            titleReference: null | string;
            /** Format: double */
            landAreaSqm: null | number;
        };
        UpdateProjectRequest: {
            code: string;
            name: string;
            site: components["schemas"]["SiteDto"];
            stage: null | components["schemas"]["ProjectStage"];
            status: null | components["schemas"]["ProjectStatus"];
            /** Format: date */
            plannedStart: null | string;
            /** Format: date */
            plannedCompletion: null | string;
            /** Format: date */
            actualStart: null | string;
            /** Format: date */
            actualCompletion: null | string;
            /** Format: double */
            budgetAmount: null | number;
            projectManager: null | string;
            description: null | string;
            /** Format: int64 */
            version: number;
        };
        VersionRequest: {
            /** Format: int64 */
            version: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientConfig"];
                };
            };
        };
    };
    GetMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    ListProjects: {
        parameters: {
            query?: {
                Stage?: components["schemas"]["ProjectStage"];
                Status?: components["schemas"]["ProjectStatus"];
                Search?: string;
                IncludeArchived?: boolean;
                Page?: number;
                PageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedResultOfProjectListItem"];
                };
            };
        };
    };
    CreateProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetails"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    GetProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UpdateProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProjectRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetails"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ArchiveProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VersionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RestoreProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VersionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
